export { queryKeys } from './keys'

export { useLogin, useRegister, useForgotPassword, useResetPassword, useMe } from './auth.query'
export { useClinics, useClinic, useCreateClinic } from './clinic.query'
export { usePatients, usePatient, useMedicalCard, useVisits } from './patient.query'
export { useAppointments, useSchedule, useCreateAppointment } from './schedule.query'
export { useAnalytics } from './analytics.query'
export { useProducts, useProduct, useOrders, useCreateOrder } from './shop.query'
export { useCourses, useCourse, useEnrollCourse } from './school.query'
export { useNotifications, useUnreadCount, useMarkNotificationRead, useMarkAllNotificationsRead } from './notification.query'
export { useAIQuery, useProactiveAlerts } from './ai.query'
