export const queryKeys = {
  auth: ['auth'] as const,
  clinics: ['clinics'] as const,
  clinic: (id: string) => ['clinic', id] as const,
  // Base keys (arrays). Clinic-scoped queries should spread + append clinicId:
  //   queryKey: [...queryKeys.patients, safeClinicId]
  // This keeps backward compatibility while making cache clinic-specific.
  patients: ['patients'] as const,
  patient: (id: string) => ['patient', id] as const,
  appointments: ['appointments'] as const,
  schedule: (clinicId: string, date?: string) => ['schedule', clinicId, date] as const,
  medicalCard: (patientId: string) => ['medicalCard', patientId] as const,
  visits: (patientId: string) => ['visits', patientId] as const,
  analytics: ['analytics'] as const,
  products: ['products'] as const,
  product: (id: string) => ['product', id] as const,
  courses: ['courses'] as const,
  course: (id: string) => ['course', id] as const,
  notifications: ['notifications'] as const,
  receipts: ['receipts'] as const,
  inventory: ['inventory'] as const,
  labOrders: ['labOrders'] as const,
  expenses: ['expenses'] as const,
  promotions: ['promotions'] as const,
  bookings: ['bookings'] as const,
  documents: ['documents'] as const,
  waitingList: ['waitingList'] as const,
  chairs: ['chairs'] as const,
  users: ['users'] as const,
  photos: ['photos'] as const,
  subscriptions: ['subscriptions'] as const,
  treatments: ['treatments'] as const,
  admin: {
    stats: ['admin', 'stats'] as const,
    clinics: ['admin', 'clinics'] as const,
    clinic: (id: string) => ['admin', 'clinic', id] as const,
    users: (params?: Record<string, string>) => ['admin', 'users', params] as const,
    support: ['admin', 'support'] as const,
  },
  diagnostics: {
    dashboard: (clinicId?: string) => ['diagnostics', 'dashboard', clinicId] as const,
    referrals: (params?: Record<string, string>) => ['diagnostics', 'referrals', params] as const,
    referral: (id: string) => ['diagnostics', 'referral', id] as const,
    centers: (search?: string) => ['diagnostics', 'centers', search] as const,
    center: (id: string) => ['diagnostics', 'center', id] as const,
    labs: (search?: string) => ['diagnostics', 'labs', search] as const,
    studies: (centerId?: string) => ['diagnostics', 'studies', centerId] as const,
    labTests: (labId?: string) => ['diagnostics', 'labTests', labId] as const,
    centerPricing: (centerId: string) => ['diagnostics', 'centerPricing', centerId] as const,
    labPricing: (labId: string) => ['diagnostics', 'labPricing', labId] as const,
    centerPayments: (centerId: string) => ['diagnostics', 'centerPayments', centerId] as const,
    labPayments: (labId: string) => ['diagnostics', 'labPayments', labId] as const,
  },
}