import React, { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Activity, ArrowRight, BarChart3, Bot, BriefcaseBusiness, Calendar, CheckCircle2, Clock, CreditCard, DollarSign, FlaskConical, GraduationCap, HeartPulse, Package, Settings, ShoppingCart, SlidersHorizontal, Sparkles, Stethoscope, Users, X } from 'lucide-react'
import { cn, getGreeting, formatMoney } from '@/lib/utils'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/ds/Card'
import { PageHeader, StatCard } from '@/components/ui/ds/StatCard'
import { Badge } from '@/components/ui/ds/Badge'
import { Button } from '@/components/ui/ds/Button'
import { useAuth } from '@/store/auth.store'
import { useDataQuery } from '@/queries/useDataQuery'
import { getMyProfile, updateMyProfile } from '@/utils/api'

const container = { hidden: { opacity: 0 }, show: { opacity: 1, transition: { staggerChildren: 0.045 } } }
const item = { hidden: { opacity: 0, y: 8 }, show: { opacity: 1, y: 0, transition: { duration: 0.24, ease: 'easeOut' } } }

type ServiceId = 'clinic' | 'diagnostics' | 'medical-lab' | 'dental-lab' | 'shop' | 'academy' | 'jobs' | 'network' | 'ai' | 'analytics' | 'finance' | 'settings'
type ServiceTile = { id: ServiceId; title: string; subtitle: string; icon: React.ElementType; path: string }

const SERVICE_TILES: ServiceTile[] = [
  { id: 'ai', title: 'DentVision AI', subtitle: 'Командный слой экосистемы', icon: Bot, path: '/ai' },
  { id: 'clinic', title: 'Практика', subtitle: 'Пациенты, случаи и расписание', icon: Stethoscope, path: '/crm/schedule' },
  { id: 'diagnostics', title: 'Диагностика', subtitle: 'Рентген, исследования и результаты', icon: FlaskConical, path: '/diagnostics' },
  { id: 'medical-lab', title: 'Медицинская лаборатория', subtitle: 'Анализы, результаты и заказы', icon: HeartPulse, path: '/diagnostics/lab' },
  { id: 'dental-lab', title: 'Зуботехническая лаборатория', subtitle: 'Заказы, производство и выдача', icon: Package, path: '/crm/lab' },
  { id: 'shop', title: 'DentVision Market', subtitle: 'Материалы, оборудование и закупки', icon: ShoppingCart, path: '/shop' },
  { id: 'academy', title: 'Academy', subtitle: 'Курсы, практика и развитие', icon: GraduationCap, path: '/school' },
  { id: 'jobs', title: 'Jobs', subtitle: 'Вакансии и профессиональные возможности', icon: BriefcaseBusiness, path: '/jobs' },
  { id: 'network', title: 'Network', subtitle: 'Специалисты и организации', icon: Users, path: '/community' },
  { id: 'analytics', title: 'Аналитика', subtitle: 'Показатели и решения', icon: BarChart3, path: '/analytics' },
  { id: 'finance', title: 'Finance', subtitle: 'Платежи и экономика', icon: CreditCard, path: '/crm/cashier' },
  { id: 'settings', title: 'Настройки', subtitle: 'Профиль и рабочий контекст', icon: Settings, path: '/settings' },
]

const DEFAULT_QUICK: Record<string, ServiceId[]> = {
  doctor: ['ai', 'clinic', 'diagnostics', 'academy'], owner: ['ai', 'clinic', 'analytics', 'finance'], director: ['ai', 'clinic', 'analytics', 'finance'], admin: ['ai', 'clinic', 'diagnostics', 'shop'], assistant: ['ai', 'clinic', 'diagnostics', 'shop'],
  diagnostic_center: ['ai', 'diagnostics', 'network', 'finance'], lab_diagnostic: ['ai', 'medical-lab', 'diagnostics', 'finance'], laboratory: ['ai', 'dental-lab', 'shop', 'finance'], lab: ['ai', 'dental-lab', 'shop', 'finance'],
  student: ['ai', 'academy', 'network', 'jobs'], user: ['ai', 'shop', 'academy', 'network'],
}
const FALLBACK_QUICK: ServiceId[] = ['ai', 'diagnostics', 'academy', 'shop']
const PREF_KEY = 'dentvision.home.quick-services.v3'
type ProfilePrefs = { homeQuickServices?: string[]; homeAiAutoCollapse?: boolean }

function normalizeRole(user: ReturnType<typeof useAuth>['user']) { return String(user?.platformRole || user?.role || 'user').toLowerCase() }
function getDefaultQuick(role: string): ServiceId[] { return DEFAULT_QUICK[role] || FALLBACK_QUICK }

function QuickStats({ data }: { data: ReturnType<typeof useDataQuery> }) {
  const stats = useMemo(() => { const today = new Date().toISOString().split('T')[0]; const todayAppts = (data.appointments || []).filter(a => a.date === today); const todayRevenue = (data.receipts || []).filter(r => String((r as { date?: string }).date || '').slice(0, 10) === today).reduce((s, r) => s + (Number(r.amount) || 0), 0); return { todayCount: todayAppts.length, todayRevenue, activePatients: (data.patients || []).length } }, [data])
  return <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><StatCard label="Записей сегодня" value={stats.todayCount} icon={<Calendar size={18} />} /><StatCard label="Пациентов" value={stats.activePatients} icon={<Users size={18} />} /><StatCard label="Доход сегодня" value={formatMoney(stats.todayRevenue)} icon={<DollarSign size={18} />} /><StatCard label="Загрузка (оц.)" value={`${Math.min(100, Math.round((stats.todayCount / 8) * 100))}%`} icon={<Activity size={18} />} /></div>
}

function AiSmartBanner({ collapsed, onToggle, autoCollapse, onAutoCollapseChange }: { collapsed: boolean; onToggle: () => void; autoCollapse: boolean; onAutoCollapseChange: (value: boolean) => void }) {
  useEffect(() => { if (!autoCollapse || collapsed) return; const timer = window.setTimeout(onToggle, 7000); return () => window.clearTimeout(timer) }, [autoCollapse, collapsed, onToggle])
  if (collapsed) return <motion.button initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} onClick={onToggle} className="w-full flex items-center gap-3 rounded-2xl border border-dv-gold/20 bg-dv-gold/5 px-4 py-3 text-left hover:bg-dv-gold/10 transition-colors"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-dv-gold/15 text-dv-gold"><Bot size={18} /></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold text-txt-primary">DentVision AI</span><span className="block text-2xs text-txt-muted truncate">Ваш контекст, задачи и экосистема — в одном месте</span></span><ArrowRight size={15} className="text-dv-gold" /></motion.button>
  return <motion.div layout className="relative overflow-hidden rounded-2xl border border-dv-gold/25 bg-surface-1 p-4 md:p-5 shadow-sm"><div className="relative flex gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-dv-gold/15 text-dv-gold"><Sparkles size={19} /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-semibold text-txt-primary">DentVision AI</span><Badge variant="warning" size="xs">Готов</Badge></div><p className="mt-1 text-sm text-txt-secondary">Помогает находить данные, людей, услуги и материалы и выполнять разрешённые действия в вашем текущем контексте.</p><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="primary" onClick={() => window.location.assign('/ai')}>Открыть AI</Button><button type="button" onClick={onToggle} className="px-3 text-xs text-txt-muted hover:text-txt-primary">Свернуть</button></div></div><button type="button" onClick={onToggle} aria-label="Свернуть AI" className="h-8 w-8 rounded-lg text-txt-muted hover:bg-surface-2"><X size={16} /></button></div><label className="relative mt-3 flex items-center gap-2 text-2xs text-txt-muted cursor-pointer"><input type="checkbox" checked={autoCollapse} onChange={e => onAutoCollapseChange(e.target.checked)} /> Автоматически сворачивать</label></motion.div>
}

function EcosystemGrid() { const navigate = useNavigate(); return <div><div className="mb-3 px-1"><h3 className="text-sm font-semibold text-txt-secondary">Экосистема DentVision</h3><p className="mt-0.5 text-2xs text-txt-muted">Выберите направление. Глубокие рабочие инструменты откроются внутри контекста.</p></div><div className="grid grid-cols-2 sm:grid-cols-3 xl:grid-cols-4 gap-2.5">{SERVICE_TILES.map(tile => { const Icon = tile.icon; return <motion.button type="button" key={tile.id} variants={item} whileHover={{ y: -2 }} whileTap={{ scale: .98 }} onClick={() => navigate(tile.path)} className="group relative min-w-0 overflow-hidden rounded-2xl border border-bdr-subtle bg-surface-1 p-3.5 text-left hover:border-dv-gold/25 transition-all"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-dv-gold/10 text-dv-gold"><Icon size={18} /></span><h4 className="mt-2.5 truncate text-sm font-semibold text-txt-primary">{tile.title}</h4><p className="mt-0.5 line-clamp-2 text-2xs text-txt-muted">{tile.subtitle}</p><ArrowRight size={13} className="absolute right-3 top-3 text-dv-gold opacity-0 group-hover:opacity-100" /></motion.button> })}</div></div> }

function ServiceSettings({ visible, onClose, onSave }: { visible: ServiceId[]; onClose: () => void; onSave: (ids: ServiceId[]) => void }) {
  const [draft, setDraft] = useState<ServiceId[]>(visible); const toggle = (id: ServiceId) => setDraft(v => v.includes(id) ? v.filter(x => x !== id) : v.length < 4 ? [...v, id] : v); const move = (index: number, direction: -1 | 1) => setDraft(v => { const n = [...v]; const target = index + direction; if (target < 0 || target >= n.length) return v; [n[index], n[target]] = [n[target], n[index]]; return n })
  return <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center bg-black/50 p-0 sm:p-4" onMouseDown={onClose}><div className="w-full sm:max-w-lg max-h-[85vh] overflow-y-auto rounded-t-2xl sm:rounded-2xl border border-bdr-subtle bg-surface-1 p-5 shadow-2xl" onMouseDown={e => e.stopPropagation()}><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold text-txt-primary">Быстрый доступ</h2><p className="text-xs text-txt-muted mt-1">До 4 направлений. Остальная экосистема остаётся доступной в навигации.</p></div><button type="button" onClick={onClose} className="h-9 w-9 rounded-lg hover:bg-surface-2 text-txt-muted"><X size={18} /></button></div><div className="mt-5 space-y-2">{SERVICE_TILES.map(s => { const checked = draft.includes(s.id), index = draft.indexOf(s.id), Icon = s.icon; return <div key={s.id} className={cn('flex items-center gap-3 rounded-xl border p-3', checked ? 'border-dv-gold/30 bg-dv-gold/5' : 'border-bdr-subtle')}><input type="checkbox" checked={checked} onChange={() => toggle(s.id)} className="h-4 w-4" /><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-surface-2 text-dv-gold"><Icon size={17} /></span><div className="min-w-0 flex-1"><div className="text-sm font-medium text-txt-primary">{s.title}</div><div className="text-2xs text-txt-muted">{s.subtitle}</div></div>{checked && <div className="flex gap-1"><button type="button" disabled={index === 0} onClick={() => move(index, -1)} className="h-8 w-8 rounded-lg hover:bg-surface-2 disabled:opacity-30">↑</button><button type="button" disabled={index === draft.length - 1} onClick={() => move(index, 1)} className="h-8 w-8 rounded-lg hover:bg-surface-2 disabled:opacity-30">↓</button></div>}</div> })}</div><div className="mt-5 flex gap-2"><Button className="flex-1" onClick={() => onSave(draft)}>Сохранить</Button><Button variant="secondary" onClick={onClose}>Отмена</Button></div></div></div>
}

function QuickAccess({ ids, onConfigure }: { ids: ServiceId[]; onConfigure: () => void }) { const navigate = useNavigate(); const quick = ids.map(id => SERVICE_TILES.find(s => s.id === id)).filter((s): s is ServiceTile => Boolean(s)); return <div><div className="flex items-center justify-between mb-3 px-1"><div><h3 className="text-sm font-semibold text-txt-secondary">Ваши быстрые действия</h3><p className="text-2xs text-txt-muted mt-0.5">Настраивается под вашу роль и рабочий контекст.</p></div><button type="button" onClick={onConfigure} className="flex items-center gap-1.5 rounded-lg px-2.5 py-2 text-xs text-txt-muted hover:bg-surface-2 hover:text-txt-primary"><SlidersHorizontal size={14} /> Настроить</button></div><div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5">{quick.map(tile => { const Icon = tile.icon; return <motion.button type="button" key={tile.id} variants={item} whileHover={{ y: -2 }} whileTap={{ scale: .98 }} onClick={() => navigate(tile.path)} className="group relative min-w-0 overflow-hidden rounded-2xl border border-bdr-subtle bg-surface-1 p-3.5 text-left hover:border-dv-gold/25 transition-all"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-dv-gold/10 text-dv-gold"><Icon size={18} /></span><h4 className="mt-2.5 truncate text-sm font-semibold text-txt-primary">{tile.title}</h4><p className="mt-0.5 line-clamp-1 text-2xs text-txt-muted">{tile.subtitle}</p><ArrowRight size={13} className="absolute right-3 top-3 text-dv-gold opacity-0 group-hover:opacity-100" /></motion.button> })}</div></div> }

function UpcomingAppointments({ data }: { data: ReturnType<typeof useDataQuery> }) { const navigate = useNavigate(); const today = new Date().toISOString().split('T')[0]; const appointments = (data.appointments || []).filter(a => a.date >= today).sort((a, b) => (a.date + (a.time || '')).localeCompare(b.date + (b.time || ''))).slice(0, 5); const patients = data.patients || []; if (!appointments.length) return null; return <Card><CardHeader className="flex-wrap"><CardTitle className="flex items-center gap-2"><Clock size={16} className="text-dv-gold" /> Ближайшие записи</CardTitle><button type="button" onClick={() => navigate('/crm/schedule')} className="text-xs text-dv-gold min-h-11">Все записи</button></CardHeader><CardContent><div className="space-y-2">{appointments.map(appt => { const patient = patients.find(p => p.id === appt.patientId); return <div key={appt.id} className="flex items-center gap-3 rounded-lg px-3 py-2.5 bg-surface-2/50"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-dv-gold/10 text-dv-gold text-xs font-bold shrink-0">{appt.time?.slice(0, 5) || '--:--'}</div><div className="min-w-0 flex-1"><p className="text-sm font-medium text-txt-primary truncate">{patient?.name || appt.patientName || 'Пациент'}</p><p className="text-2xs text-txt-muted truncate">{appt.service || 'Приём'}</p></div><Badge variant={appt.status === 'confirmed' ? 'success' : appt.status === 'cancelled' ? 'error' : 'warning'} size="xs">{appt.status === 'confirmed' ? 'Подтверждена' : appt.status === 'cancelled' ? 'Отменена' : 'Ожидание'}</Badge></div> })}</div></CardContent></Card> }

export default function Dashboard() {
  const { user } = useAuth(); const navigate = useNavigate(); const data = useDataQuery(user?.clinicId); const role = normalizeRole(user); const hasClinicContext = Boolean(user?.clinicId)
  const [quickIds, setQuickIds] = useState<ServiceId[]>(getDefaultQuick(role)); const [settingsOpen, setSettingsOpen] = useState(false); const [aiCollapsed, setAiCollapsed] = useState(false); const [aiAutoCollapse, setAiAutoCollapse] = useState(true)
  useEffect(() => { let cancelled = false; const load = async () => { try { const profile = await getMyProfile(); if (cancelled) return; const prefs = (profile?.user || profile) as ProfilePrefs; const serverIds = Array.isArray(prefs?.homeQuickServices) ? prefs.homeQuickServices.filter((id): id is ServiceId => SERVICE_TILES.some(s => s.id === id)).slice(0, 4) : []; if (serverIds.length) setQuickIds(serverIds); else { const raw = localStorage.getItem(PREF_KEY); if (raw) { const parsed = JSON.parse(raw); if (Array.isArray(parsed)) setQuickIds(parsed.filter((id): id is ServiceId => SERVICE_TILES.some(s => s.id === id)).slice(0, 4)) } } setAiAutoCollapse(prefs?.homeAiAutoCollapse !== false) } catch { try { const raw = localStorage.getItem(PREF_KEY); if (raw) { const parsed = JSON.parse(raw); if (Array.isArray(parsed)) setQuickIds(parsed.filter((id): id is ServiceId => SERVICE_TILES.some(s => s.id === id)).slice(0, 4)) } } catch { void 0 } } }; void load(); return () => { cancelled = true } }, [user?.id])
  const persistPreferences = async (ids: ServiceId[], autoCollapse = aiAutoCollapse) => { const next = ids.slice(0, 4); setQuickIds(next); try { localStorage.setItem(PREF_KEY, JSON.stringify(next)) } catch { void 0 } try { await updateMyProfile({ homeQuickServices: next, homeAiAutoCollapse: autoCollapse }) } catch { void 0 } }
  const changeAutoCollapse = (value: boolean) => { setAiAutoCollapse(value); void persistPreferences(quickIds, value) }
  return <motion.div variants={container} initial="hidden" animate="show" className="max-w-full overflow-x-hidden mx-auto space-y-5"><motion.div variants={item}><PageHeader title={`${getGreeting()}, ${user?.name || user?.login}`} subtitle={new Date().toLocaleDateString('ru-RU', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })} actions={<div className="hidden md:flex items-center gap-2 px-3 py-1.5 rounded-lg bg-dv-gold/10 border border-dv-gold/20"><CheckCircle2 size={14} className="text-dv-gold" /><span className="text-xs font-medium text-dv-gold">Ваш DentVision</span></div>} /></motion.div><motion.div variants={item}><AiSmartBanner collapsed={aiCollapsed} onToggle={() => setAiCollapsed(v => !v)} autoCollapse={aiAutoCollapse} onAutoCollapseChange={changeAutoCollapse} /></motion.div>{hasClinicContext && <motion.div variants={item}><QuickStats data={data} /></motion.div>}<motion.div variants={item}><QuickAccess ids={quickIds} onConfigure={() => setSettingsOpen(true)} /></motion.div><motion.div variants={item}><EcosystemGrid /></motion.div>{hasClinicContext && <motion.div variants={item}><UpcomingAppointments data={data} /></motion.div>}{settingsOpen && <ServiceSettings visible={quickIds} onClose={() => setSettingsOpen(false)} onSave={ids => { void persistPreferences(ids); setSettingsOpen(false) }} />}<div className="flex items-center justify-between pt-2"><p className="text-2xs text-txt-muted">DentVision · Dental Operating System & ecosystem</p><button type="button" onClick={() => navigate('/ai')} className="text-2xs text-dv-gold hover:underline">Открыть AI</button></div></motion.div>
}
