    { label: 'Склад', icon: <Package size={16} />, path: '/crm/inventory' },
    { label: 'Аналитика', icon: <BarChart3 size={16} />, path: '/analytics' },
    { label: 'AI', icon: <Bot size={16} />, path: '/ai' },
  ]
  return <div><h3 className="text-sm font-semibold text-txt-secondary mb-3 px-1">Быстрые действия</h3><div className="flex flex-wrap gap-2">{actions.map(a => <motion.button key={a.label} whileHover={{ scale: 1.02 }} whileTap={{ scale: .98 }} onClick={() => navigate(a.path)} className="flex items-center gap-2 px-3 py-2 rounded-lg bg-surface-raised border border-bdr-subtle text-txt-secondary text-sm hover:bg-surface-raised-hover transition-all min-h-11">{a.icon}{a.label}</motion.button>)}</div></div>
}

export default function Dashboard() {
  const { user } = useAuth(); const navigate = useNavigate(); const data = useDataQuery(user?.clinicId)
  const [quickIds, setQuickIds] = useState<string[]>(DEFAULT_QUICK); const [settingsOpen, setSettingsOpen] = useState(false); const [aiCollapsed, setAiCollapsed] = useState(false); const [aiAutoCollapse, setAiAutoCollapse] = useState(true)
  useEffect(() => { let cancelled = false; const load = async () => { try { const profile = await getMyProfile(); if (cancelled) return; const prefs = (profile?.user || profile) as ProfilePrefs; const serverIds = Array.isArray(prefs?.homeQuickServices) ? prefs.homeQuickServices.filter(id => SERVICE_TILES.some(s => s.id === id)).slice(0, 8) : []; if (serverIds.length) setQuickIds(serverIds); else { const raw = localStorage.getItem(PREF_KEY); if (raw) { const parsed = JSON.parse(raw); if (Array.isArray(parsed)) setQuickIds(parsed.filter(id => SERVICE_TILES.some(s => s.id === id)).slice(0, 8)) } } setAiAutoCollapse(prefs?.homeAiAutoCollapse !== false) } catch { try { const raw = localStorage.getItem(PREF_KEY); if (raw) { const parsed = JSON.parse(raw); if (Array.isArray(parsed)) setQuickIds(parsed.filter(id => SERVICE_TILES.some(s => id === s.id)).slice(0, 8)) } } catch { void 0 } }; void load(); return () => { cancelled = true } }, [user?.id])
  const persistPreferences = async (ids: string[], autoCollapse = aiAutoCollapse) => { const next = ids.slice(0, 8); setQuickIds(next); try { localStorage.setItem(PREF_KEY, JSON.stringify(next)) } catch { void 0 } try { await updateMyProfile({ homeQuickServices: next, homeAiAutoCollapse: autoCollapse }) } catch { void 0 } }
  const changeAutoCollapse = (value: boolean) => { setAiAutoCollapse(value); void persistPreferences(quickIds, value) }
  return <motion.div variants={container} initial="hidden" animate="show" className="max-w-full overflow-x-hidden mx-auto space-y-5">
    <motion.div variants={item}><PageHeader title={`${getGreeting()}, ${user?.name || user?.login}`} subtitle={new Date().toLocaleDateString('ru-RU', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })} actions={<div className="hidden md:flex items-center gap-2 px-3 py-1.5 rounded-lg bg-dv-gold/10 border border-dv-gold/20"><Sparkles size={14} className="text-dv-gold" /><span className="text-xs font-medium text-dv-gold">AI включён</span></div>} /></motion.div>
    <motion.div variants={item}><AiSmartBanner collapsed={aiCollapsed} onToggle={() => setAiCollapsed(v => !v)} autoCollapse={aiAutoCollapse} onAutoCollapseChange={changeAutoCollapse} /></motion.div>
    {data.isError && !data.isLoading && <motion.div variants={item} className="rounded-xl border border-error/30 bg-error/10 px-4 py-3 text-sm text-txt-primary flex flex-wrap items-center gap-3"><span className="flex-1">Не удалось загрузить данные клиники. Показанные цифры могут быть неполными.</span><Button size="sm" variant="secondary" onClick={() => data.refetchCore()}>Повторить</Button></motion.div>}
    <motion.div variants={item}><QuickStats data={data} /></motion.div>
    <motion.div variants={item}><ServiceGrid quickIds={quickIds} onConfigure={() => setSettingsOpen(true)} /></motion.div>
    <motion.div variants={item}><UpcomingAppointments data={data} /></motion.div>
    <motion.div variants={item}><QuickActions /></motion.div>