/**
 * Text-to-speech for the presentation: synthesise on the server, cache by
 * content, and never let a failure reach the patient.
 *
 * Three rules shape everything here.
 *
 * **The cache key is the text.** `sha256(provider|model|voice|locale|text)` —
 * not the beat, not the plan, not the patient. "Здравствуйте, я расскажу о
 * вашем плане лечения" is synthesised once for the whole platform, and
 * re-watching a plan costs nothing by construction. Regenerating a script only
 * re-synthesises the lines that actually changed.
 *
 * **Silence is a valid outcome.** If storage is not configured, or OpenAI is
 * down, or the text is empty, the caller gets `null` for that line and the
 * presentation plays it on its estimated reading time instead. The patient is
 * never shown an error, because a plan they cannot hear is still a plan they
 * can read.
 *
 * **This is not a patient document.** Voice is generated by us, belongs in no
 * Documents tab, and must not be deletable through the files UI — so it goes
 * through `lib/storage.ts` directly and deliberately does *not* touch the
 * `files` routes' extension allowlist or the `ImageType` enum. Please do not
 * "fix" that by adding audio to either.
 */

import { createHash } from 'node:crypto';

import prisma from '../../lib/prisma.js';
import { env } from '../../config.js';
import { signedDownloadUrl, storageConfigured, toStorageUrl, keyFromStorageUrl, uploadObject } from '../../lib/storage.js';
import type { PresentationLocale } from './beats.js';

const TTS_ENDPOINT = 'https://api.openai.com/v1/audio/speech';
const TTS_MODEL = 'gpt-4o-mini-tts';
const TTS_FORMAT = 'mp3';
const REQUEST_TIMEOUT_MS = 20_000;

/** Signed URLs outlive an act comfortably without being worth stealing. */
const SIGNED_URL_TTL_SECONDS = 900;

/**
 * One calm, unhurried voice per locale. Deliberately not configurable per
 * clinic yet: the persona is the product's, and a per-clinic voice would
 * fragment the cache for no benefit anyone has asked for.
 */
const VOICE_BY_LOCALE: Record<PresentationLocale, string> = {
  ru: 'sage',
  kk: 'sage',
  en: 'sage',
};

/**
 * A whole narration is about this long. The cap is per request rather than per
 * day so a runaway script cannot bill in one call; beats are separately capped
 * at 320 characters by the script validator.
 */
export const MAX_CHARS_PER_REQUEST = 6_000;

export interface VoiceLine {
  beatId: string;
  text: string;
}

export interface VoiceResult {
  beatId: string;
  /** `null` means "play this one silently" — never an error to the patient. */
  audioUrl: string | null;
  durationMs: number | null;
}

export function voiceConfigured(): boolean {
  return Boolean(env.OPENAI_API_KEY) && storageConfigured();
}

/** Collapse whitespace so trivially different strings share one cache entry. */
export function normalizeForTts(text: string): string {
  return String(text ?? '').replace(/\s+/g, ' ').trim();
}

export function voiceCacheKey(text: string, locale: PresentationLocale): string {
  const voice = VOICE_BY_LOCALE[locale];
  return createHash('sha256')
    .update(`openai|${TTS_MODEL}|${voice}|${locale}|${normalizeForTts(text)}`)
    .digest('hex');
}

async function synthesizeOnce(text: string, locale: PresentationLocale): Promise<Buffer | null> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);
  try {
    const response = await fetch(TTS_ENDPOINT, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${env.OPENAI_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: TTS_MODEL,
        voice: VOICE_BY_LOCALE[locale],
        input: text,
        response_format: TTS_FORMAT,
        // The persona explains; it does not sell. An advertising read is the
        // fastest way to make a premium clinic sound like a call centre.
        instructions: 'Speak calmly and warmly, unhurried, with natural pauses. Do not sound like an advertisement.',
      }),
      signal: controller.signal,
    });
    if (!response.ok) {
      console.warn(`[Voice] synthesis failed: ${response.status}`);
      return null;
    }
    return Buffer.from(await response.arrayBuffer());
  } catch (err) {
    // Timeout, network, abort — all the same to the caller: no audio, carry on.
    console.warn('[Voice] synthesis error:', err);
    return null;
  } finally {
    clearTimeout(timer);
  }
}

/**
 * Resolve audio for a batch of lines, synthesising only what is missing.
 *
 * Returns one entry per input line, in order, with `audioUrl: null` wherever
 * synthesis was impossible. Never throws for a provider or storage problem —
 * the only way this rejects is a database failure, which is not this layer's
 * business to swallow.
 */
export async function resolveVoiceLines(
  lines: VoiceLine[],
  locale: PresentationLocale,
): Promise<VoiceResult[]> {
  const prepared = lines.map((line) => ({
    beatId: line.beatId,
    text: normalizeForTts(line.text),
  }));

  if (!voiceConfigured()) {
    // Configuration is a deployment fact, not a patient-visible failure.
    return prepared.map((l) => ({ beatId: l.beatId, audioUrl: null, durationMs: null }));
  }

  const keyed = prepared.map((l) => ({ ...l, cacheKey: voiceCacheKey(l.text, locale) }));
  const wanted = [...new Set(keyed.filter((l) => l.text).map((l) => l.cacheKey))];

  const existing = await prisma.voiceAsset.findMany({ where: { cacheKey: { in: wanted } } });
  const byKey = new Map(existing.map((asset) => [asset.cacheKey, asset]));

  // Touch what we served, so a later eviction pass can tell cold from hot.
  if (existing.length) {
    await prisma.voiceAsset
      .updateMany({ where: { cacheKey: { in: existing.map((a) => a.cacheKey) } }, data: { lastUsedAt: new Date() } })
      .catch(() => undefined);
  }

  const misses = keyed.filter((l) => l.text && !byKey.has(l.cacheKey));
  // Deduplicate within the batch too: two beats with identical wording must
  // not be synthesised twice in the same request.
  const uniqueMisses = new Map(misses.map((l) => [l.cacheKey, l]));

  let budget = MAX_CHARS_PER_REQUEST;
  for (const miss of uniqueMisses.values()) {
    if (miss.text.length > budget) {
      console.warn('[Voice] per-request character budget exhausted; remaining lines stay silent');
      break;
    }
    const audio = await synthesizeOnce(miss.text, locale);
    if (!audio) continue;
    budget -= miss.text.length;

    const key = `voice/${locale}/${miss.cacheKey}.mp3`;
    try {
      await uploadObject(key, audio, 'audio/mpeg');
    } catch (err) {
      console.warn('[Voice] upload failed:', err);
      continue;
    }

    const asset = await prisma.voiceAsset.upsert({
      where: { cacheKey: miss.cacheKey },
      // A concurrent request may have stored the same key between our read and
      // this write; upsert makes that a no-op rather than a crash.
      update: { lastUsedAt: new Date() },
      create: {
        cacheKey: miss.cacheKey,
        locale,
        voice: VOICE_BY_LOCALE[locale],
        model: TTS_MODEL,
        storageUrl: toStorageUrl(key),
        bytes: audio.byteLength,
      },
    });
    byKey.set(miss.cacheKey, asset);
  }

  return Promise.all(
    keyed.map(async (line) => {
      const asset = byKey.get(line.cacheKey);
      if (!asset) return { beatId: line.beatId, audioUrl: null, durationMs: null };
      const key = keyFromStorageUrl(asset.storageUrl);
      if (!key) return { beatId: line.beatId, audioUrl: null, durationMs: null };
      try {
        return {
          beatId: line.beatId,
          audioUrl: await signedDownloadUrl(key, SIGNED_URL_TTL_SECONDS),
          durationMs: asset.durationMs ?? null,
        };
      } catch {
        return { beatId: line.beatId, audioUrl: null, durationMs: null };
      }
    }),
  );
}
