import React,{useMemo,useState}from'react'
import{Activity,ChevronDown,FileText,Image as ImageIcon,Stethoscope}from'lucide-react'
import{Card}from'./ui/ds/Card'
import{Button}from'./ui/ds/Button'
import{Badge}from'./ui/ds/Badge'
import{AnatomicalToothSvg}from'./odontogram/AnatomicalToothSvg'
import{SurfaceEditor}from'./Odontogram3D'
import{archTeeth,normalizeTooth,STATUS_META,statusLabel,type Dentition,type PatientTeeth,type ToothData,type ToothStatusKey}from'@/lib/odontogram'
import{cn}from'@/lib/utils'
interface Props{patientTeeth?:PatientTeeth;selectedTooth?:number;onToothClick:(n:number)=>void;onApplyStatus?:(n:number,s:string)=>void;onToothDataChange?:(n:number,d:ToothData)=>void;onAction?:(a:'note'|'photo'|'clear',n?:number)=>void;dentition?:Dentition;onDentitionChange?:(d:Dentition)=>void}
export function ClinicalOdontogram({patientTeeth={},selectedTooth,onToothClick,onApplyStatus,onToothDataChange,onAction,dentition='permanent',onDentitionChange}:Props){
 const[tool,setTool]=useState<ToothStatusKey|null>(null),[open,setOpen]=useState(true)
 const upper=archTeeth(dentition,true),lower=archTeeth(dentition,false)
 const selected=selectedTooth?normalizeTooth(patientTeeth[selectedTooth]??patientTeeth[String(selectedTooth)]):null
 const status=selected?.status||'healthy'
 const diagnosis=selected?.diagnosis?.trim()||''
 const surfaces=Object.entries(selected?.surfaces||{}).filter(([,v])=>v)
 const issues=useMemo(()=>Object.entries(patientTeeth).filter(([,r])=>{const t=normalizeTooth(r);return t.status!=='healthy'||Object.keys(t.surfaces||{}).length>0}).length,[patientTeeth])
 const tools=['caries','filled','crown','implant','fracture','inflammation','missing','root','veneer','endo_ok','endo_fail'] as const
 const tooth=(n:number,upperArch:boolean)=>{const t=normalizeTooth(patientTeeth[n]??patientTeeth[String(n)]),active=selectedTooth===n;return <div key={n} className="flex flex-1 justify-center min-w-0"><button type="button" aria-label={'Зуб '+n+(t.status&&t.status!=='healthy'?', '+statusLabel(t.status):'')} onClick={()=>{if(tool&&onApplyStatus)onApplyStatus(n,tool);onToothClick(n)}} className={cn('relative flex w-full max-w-[58px] justify-center rounded-xl p-0.5 focus:outline-none focus-visible:ring-2 focus-visible:ring-dv-gold/60',active&&'bg-dv-gold/10 ring-1 ring-dv-gold/60')}><AnatomicalToothSvg toothNumber={n} status={t.status} surfaces={t.surfaces} selected={active} size={46} view="buccal" showLabels={false}/><span className={cn('absolute left-1/2 -translate-x-1/2 text-[9px] tabular-nums',upperArch?'-bottom-4':'-top-4',active?'text-dv-gold':'text-txt-muted')}>{n}</span></button></div>}
 return <Card padding="none" className="overflow-hidden"><div className="border-b border-bdr-subtle px-4 py-3 flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><Stethoscope size={17} className="text-dv-gold"/><h3 className="m-0 text-sm font-semibold text-txt-primary">Одонтограмма</h3>{issues>0&&<Badge variant="warning" size="sm">{issues}</Badge>}</div><p className="m-0 mt-0.5 text-[11px] text-txt-muted">Анатомия · FDI · M/O/D/B/L · клинический контекст</p></div><div className="flex gap-1 rounded-lg border border-bdr-subtle p-0.5">{(['permanent','primary']as const).map(m=><button key={m} type="button" aria-pressed={dentition===m} onClick={()=>onDentitionChange?.(m)} className={cn('rounded-md px-3 py-1.5 text-[11px]',dentition===m?'bg-surface-2 text-txt-primary':'text-txt-muted')}>{m==='permanent'?'Постоянные':'Молочные'}</button>)}</div></div>
 <div className="grid xl:grid-cols-[minmax(0,1fr)_320px]"><section className="min-w-0 px-3 py-7 sm:px-5"><div className="mx-auto max-w-[920px]"><div className="mb-5 text-center text-[10px] uppercase tracking-[.16em] text-txt-muted">Верхняя челюсть</div><div className="flex gap-1 sm:gap-2">{upper.map(n=>tooth(n,true))}</div><div className="my-9 border-t border-dashed border-bdr-subtle"/><div className="mb-5 text-center text-[10px] uppercase tracking-[.16em] text-txt-muted">Нижняя челюсть</div><div className="flex gap-1 sm:gap-2">{lower.map(n=>tooth(n,false))}</div></div><div className="mt-10 flex flex-wrap justify-center gap-1.5">{tools.map(s=><button key={s} type="button" aria-pressed={tool===s} onClick={()=>setTool(tool===s?null:s)} className={cn('rounded-lg border px-2 py-1.5 text-[10px]',tool===s?'border-dv-gold/50 bg-dv-gold/10 text-txt-primary':'border-bdr-subtle text-txt-secondary')}><i className="mr-1.5 inline-block h-2 w-2 rounded-full" style={{background:STATUS_META[s].color}}/>{STATUS_META[s].label}</button>)}</div><div className="mt-3 text-center text-[10px] text-txt-muted">{tool?STATUS_META[tool].label+': выберите зуб':'Выберите зуб для редактирования'}</div></section>
 <aside className={cn('border-t border-bdr-subtle bg-surface-1/40 xl:border-l xl:border-t-0',!open&&'hidden xl:block')}><div className="flex items-center justify-between border-b border-bdr-subtle px-4 py-3"><div className="flex items-center gap-2"><Activity size={15} className="text-dv-gold"/><span className="text-xs font-semibold">Клинический контекст</span></div><button type="button" onClick={()=>setOpen(!open)} aria-label="Свернуть"><ChevronDown size={15}/></button></div>{!selectedTooth?<div className="px-5 py-10 text-center"><Stethoscope size={20} className="mx-auto mb-3 text-txt-muted"/><p className="m-0 text-xs text-txt-secondary">Выберите зуб</p><p className="m-0 mt-1 text-[10px] text-txt-muted">Диагноз, поверхности и действия появятся здесь.</p></div>:<div className="space-y-4 p-4"><div className="flex justify-between gap-2"><div><div className="text-lg font-bold text-dv-gold">Зуб {selectedTooth}</div><div className="text-[10px] text-txt-muted">{status==='healthy'?'Без отмеченных состояний':STATUS_META[status]?.label||statusLabel(status)}</div></div><Badge variant={status==='healthy'?'default':'warning'} size="sm">{status==='healthy'?'Норма':'Находка'}</Badge></div><div className="rounded-xl border border-bdr-subtle bg-surface-2/50 p-3"><div className="mb-2 text-[9px] uppercase tracking-wide text-txt-muted">Клиническая оценка</div><div className="grid grid-cols-2 gap-2 mb-3"><div><div className="text-[9px] uppercase tracking-wide text-txt-muted">Диагноз</div><div className="mt-1 text-[11px] text-txt-primary">{diagnosis||'Не указан'}</div></div><div><div className="text-[9px] uppercase tracking-wide text-txt-muted">Заметка</div><div className="mt-1 text-[11px] text-txt-primary line-clamp-2">{selected?.notes?.trim()||'Нет заметки'}</div></div></div><div className="mb-2 text-[9px] uppercase tracking-wide text-txt-muted">Поверхности</div>{surfaces.length?<div className="grid grid-cols-5 gap-1">{surfaces.map(([s,v])=><div key={s} className="rounded-lg border border-bdr-subtle p-2 text-center"><b className="text-xs">{s}</b><div className="text-[8px] text-txt-muted">{statusLabel(String(v))}</div></div>)}</div>:<div className="text-[10px] text-txt-muted">Нет отметок</div>}</div><div className="grid grid-cols-3 gap-1.5"><Button size="sm" variant="secondary" onClick={()=>onAction?.('note',selectedTooth)} icon={<FileText size={13}/>}>Заметка</Button><Button size="sm" variant="secondary" onClick={()=>onAction?.('photo',selectedTooth)} icon={<ImageIcon size={13}/>}>Фото</Button><Button size="sm" variant="secondary" onClick={()=>onAction?.('clear',selectedTooth)}>Очистить</Button></div>{onToothDataChange&&<SurfaceEditor toothNumber={selectedTooth} tooth={patientTeeth[selectedTooth]??patientTeeth[String(selectedTooth)]} onSave={onToothDataChange} onCancel={()=>onToothClick(selectedTooth)}/>}</div>}</aside></div></Card>}
export default ClinicalOdontogram
