import { Router } from 'express';
import { createHash } from 'node:crypto';
import prisma from '../../lib/prisma.js';
import { syncTeeth } from './teethStore.js';
import { authenticate } from '../../middleware/auth.js';
import { requirePermission } from '../../middleware/rbac.js';
import { publish } from '../../lib/events.js';
import { auditFromReq } from '../compliance/audit.service.js';
import { uid, paginate, paginatedResponse, stripHtmlTags } from '../../lib/helpers.js';
import type { AuthRequest, ApiResponse } from '../../types/index.js';
import type { Prisma } from '@prisma/client';
import { loadClinicAccess, requireClinicWritable, guardPatientCreate } from '../../middleware/planGate.js';
import { buildPatientIinFields, IinValidationError, type PatientIinFields } from '../../lib/patientIin.js';
import { decryptField, hmacIin } from '../../lib/phi.js';
import { normalizeIin, iinBirthDate, iinSex } from '../../lib/iin.js';
import { ensurePatientAssignment, revokePatientAssignment, isAssignmentRole } from '../../lib/patientAssignment.js';
import { isClinicMember } from '../../lib/orgContext.js';
import { reserveIdempotencyKey, completeIdempotencyKey, deleteIdempotencyKey } from '../../lib/idempotency.js';

export const patientsRouter = Router();
patientsRouter.use(authenticate);
patientsRouter.use(loadClinicAccess);

function splitName(name?: string, firstName?: string, lastName?: string) {
  if (firstName || lastName) return { firstName: stripHtmlTags(firstName || name || 'Пациент') || 'Пациент', lastName: stripHtmlTags(lastName || '') || '-' };
  const parts = stripHtmlTags(name).split(/\s+/).filter(Boolean);
  if (!parts.length) return { firstName: 'Пациент', lastName: '-' };
  return parts.length === 1 ? { firstName: parts[0], lastName: '-' } : { firstName: parts[0], lastName: parts.slice(1).join(' ') };
}

function serializePatient(p: any) {
  const history = (p.medicalHistory && typeof p.medicalHistory === 'object' ? p.medicalHistory : {}) as Record<string, unknown>;
  const teeth: Record<string, unknown> = {};
  if (history.teeth && typeof history.teeth === 'object') Object.assign(teeth, history.teeth as object);
  if (Array.isArray(p.teeth)) for (const t of p.teeth) {
    let surfaces: Record<string, string> | undefined;
    if (t.notes) { try { const x = JSON.parse(t.notes); if (x && typeof x === 'object' && x.surfaces) surfaces = x.surfaces; } catch {} }
    const key = String(t.number), existing = teeth[key];
    if (existing && typeof existing === 'object') { const e = existing as Record<string, unknown>; if (!e.status && t.condition) e.status = t.condition; if (!e.surfaces && surfaces) e.surfaces = surfaces; }
    else teeth[key] = { status: t.condition || 'healthy', diagnosis: t.diagnosis, notes: surfaces ? null : t.notes, ...(surfaces ? { surfaces } : {}) };
  }
  return { id:p.id, clinicId:p.clinicId, name:`${p.firstName} ${p.lastName}`.trim(), firstName:p.firstName, lastName:p.lastName, phone:p.phone||'', email:p.email||'', dob:p.birthDate?p.birthDate.toISOString().slice(0,10):'', birthDate:p.birthDate, gender:p.gender||'', address:p.address||'', notes:p.notes||'', iin:decryptField(p.iin??null)||'', noIinReason:p.noIinReason||'', prepaidBalance:Number(p.prepaidBalance||0), category:(history.category as string)||'regular', source:(history.source as string)||'', allergies:(history.allergies as string)||'', tags:Array.isArray(history.tags)?history.tags:[], teeth, medicalHistory:history, createdAt:p.createdAt, updatedAt:p.updatedAt };
}

patientsRouter.get('/', async (req: AuthRequest, res) => {
  try {
    const clinicId=req.user?.clinicId; if(!clinicId) return res.status(400).json({ok:false,error:'Клиника не указана'} satisfies ApiResponse);
    const page=parseInt(req.query.page as string)||1, limit=Math.min(parseInt(req.query.limit as string)||100,500), search=(req.query.search as string)||''; const {skip,take}=paginate(page,limit);
    const iin=normalizeIin(search), iinHash=iin.length===12?hmacIin(iin):null;
    const where={clinicId,...(iinHash?{iinHash}:search?{OR:[{firstName:{contains:search,mode:'insensitive' as const}},{lastName:{contains:search,mode:'insensitive' as const}},{phone:{contains:search,mode:'insensitive' as const}},{email:{contains:search,mode:'insensitive' as const}}]}:{})};
    const [rows,total]=await Promise.all([prisma.patient.findMany({where,skip,take,include:{teeth:true},orderBy:{createdAt:'desc'}}),prisma.patient.count({where})]);
    return res.json({ok:true,data:paginatedResponse(rows.map(serializePatient),total,page,limit)} satisfies ApiResponse);
  } catch(e){console.error('List patients error:',e);return res.status(500).json({ok:false,error:'Ошибка при получении списка пациентов'} satisfies ApiResponse)}
});

patientsRouter.post('/', requirePermission('patient.write'), guardPatientCreate, async (req: AuthRequest,res) => {
  let idempotencyKey:string|undefined, completed=false;
  try {
    const clinicId=req.user?.clinicId; if(!clinicId) return res.status(400).json({ok:false,error:'Клиника не указана'} satisfies ApiResponse);
    const body=req.body||{}, {firstName,lastName}=splitName(body.name,body.firstName,body.lastName), id=body.id||uid();
    const history:Record<string,unknown>={...(body.medicalHistory&&typeof body.medicalHistory==='object'?body.medicalHistory:{})};
    for(const k of ['category','source','allergies','tags','teeth']) if(body[k]) history[k]=body[k];
    if(!body.id){idempotencyKey=req.headers['idempotency-key'] as string|undefined;if(!idempotencyKey) idempotencyKey=`server-${createHash('sha256').update(`${req.user!.id}:${clinicId}:${JSON.stringify(body)}`).digest('hex').slice(0,32)}`;const r=await reserveIdempotencyKey(idempotencyKey);if(r.status==='in_flight') return res.status(409).json({ok:false,error:'Пациент уже создаётся, повторите позже'} satisfies ApiResponse);if(r.status==='exists'){const prior=await prisma.patient.findUnique({where:{id:r.resultId},include:{teeth:true}});if(prior)return res.json({ok:true,data:serializePatient(prior)} satisfies ApiResponse);await deleteIdempotencyKey(idempotencyKey)}}
    const existing=body.id?await prisma.patient.findFirst({where:{id:body.id,clinicId}}):null;
    const iinTouched=body.iin!==undefined||body.noIinReason!==undefined; let iinFields:PatientIinFields|undefined;
    if(!existing||iinTouched) iinFields=await buildPatientIinFields({iin:body.iin,noIinReason:body.noIinReason,clinicId,excludePatientId:existing?.id,birthDate:(body.dob||body.birthDate)??existing?.birthDate??null,gender:body.gender??existing?.gender??null,required:!existing});
    const data={firstName,lastName,phone:body.phone??existing?.phone??null,email:body.email??existing?.email??null,birthDate:(body.dob||body.birthDate)?new Date(body.dob||body.birthDate):existing?.birthDate??null,gender:body.gender??existing?.gender??null,address:body.address??existing?.address??null,notes:body.notes??existing?.notes??null,iin:iinFields?iinFields.iin:(existing as any)?.iin,iinHash:iinFields?.iinHash,noIinReason:iinFields?.noIinReason,medicalHistory:history as Prisma.InputJsonValue};
    const patient=existing?await prisma.patient.update({where:{id:existing.id},data,include:{teeth:true}}):await prisma.patient.create({data:{...data,id,clinicId,iin:iinFields!.iin,iinHash:iinFields!.iinHash,noIinReason:iinFields!.noIinReason},include:{teeth:true}});
    if(body.teeth) await syncTeeth(patient.id,body.teeth);
    const refreshed=await prisma.patient.findUnique({where:{id:patient.id},include:{teeth:true}});
    if(!existing){const c=history.complaints??history.chiefComplaint??body.complaints??body.chiefComplaint;publish('patient.created',{clinicId,patientId:patient.id,userId:req.user?.id,name:`${firstName} ${lastName}`.trim(),...(c?{complaints:Array.isArray(c)?c.map(String).slice(0,12):[String(c).slice(0,500)]}: {})});}
    else await auditFromReq(req,{action:'patient.updated',entity:'patient',entityId:patient.id,details:{name:`${firstName} ${lastName}`.trim()}});
    if(idempotencyKey){await completeIdempotencyKey(idempotencyKey,patient.id);completed=true;}
    return res.status(existing?200:201).json({ok:true,data:serializePatient(refreshed!)} satisfies ApiResponse);
  }catch(e){if(idempotencyKey&&!completed) await deleteIdempotencyKey(idempotencyKey).catch(()=>undefined);if(e instanceof IinValidationError)return res.status((e as any).code==='DUPLICATE'?409:400).json({ok:false,error:e.message} satisfies ApiResponse);console.error('Upsert patient error:',e);return res.status(500).json({ok:false,error:'Ошибка при сохранении пациента'} satisfies ApiResponse)}
});

patientsRouter.get('/lookup',requirePermission('patient.read'),async(req:AuthRequest,res)=>{try{const clinicId=req.user?.clinicId;if(!clinicId)return res.status(400).json({ok:false,error:'Клиника не указана'} satisfies ApiResponse);const iin=normalizeIin(req.query.iin);if(iin.length!==12)return res.status(400).json({ok:false,error:'ИИН должен состоять из 12 цифр'} satisfies ApiResponse);const hash=hmacIin(iin);const existing=await prisma.patient.findFirst({where:{clinicId,iinHash:hash,deletedAt:null},select:{id:true,firstName:true,lastName:true,phone:true}});const suggested=!existing?await prisma.patient.findFirst({where:{iinHash:hash,deletedAt:null,clinicId:{not:clinicId}},orderBy:{updatedAt:'desc'},select:{firstName:true,lastName:true,phone:true,email:true}}):null;await auditFromReq(req,{action:'patient.iin_lookup',entity:'patient',entityId:existing?.id||null,details:{found:!!existing,suggested:!!suggested}});return res.json({ok:true,data:{derived:{birthDate:iinBirthDate(iin),gender:iinSex(iin)},existing:existing?{id:existing.id,name:`${existing.firstName} ${existing.lastName}`.trim(),phone:existing.phone||''}:null,suggested:suggested?{name:`${suggested.firstName} ${suggested.lastName}`.trim(),phone:suggested.phone||'',email:suggested.email||''}:null}} satisfies ApiResponse)}catch(e){console.error('Patient IIN lookup error:',e);return res.status(500).json({ok:false,error:'Не удалось проверить ИИН'} satisfies ApiResponse)}});

patientsRouter.get('/:id/summary',async(req:AuthRequest,res)=>{try{const clinicId=req.user?.clinicId;if(!clinicId)return res.status(400).json({ok:false,error:'Клиника не указана'} satisfies ApiResponse);const p=await prisma.patient.findFirst({where:{id:req.params.id,clinicId},include:{teeth:true}});if(!p)return res.status(404).json({ok:false,error:'Пациент не найден'} satisfies ApiResponse);const now=new Date();const [nextAppt,openPlans,unpaid,paid]=await Promise.all([prisma.appointment.findFirst({where:{patientId:p.id,clinicId,date:{gte:now},status:{notIn:['cancelled','no_show','completed']}},orderBy:[{date:'asc'},{time:'asc'}]}),prisma.treatmentPlan.count({where:{patientId:p.id,status:{in:['draft','proposed','accepted','in_progress','active']}}}),prisma.invoice.aggregate({where:{clinicId,patientId:p.id,status:{in:['pending','unpaid','partial','overdue']}},_sum:{amount:true}}),prisma.invoice.aggregate({where:{clinicId,patientId:p.id,status:'paid'},_sum:{amount:true}})]);return res.json({ok:true,data:{patient:serializePatient(p),balance:unpaid._sum.amount||0,paidTotal:paid._sum.amount||0,openPlans,nextVisit:nextAppt?{id:nextAppt.id,date:nextAppt.date.toISOString().slice(0,10),time:nextAppt.time,status:nextAppt.status,service:nextAppt.type}:null}} satisfies ApiResponse)}catch(e){console.error('Patient summary error:',e);return res.status(500).json({ok:false,error:'Не удалось получить сводку пациента'} satisfies ApiResponse)}});

patientsRouter.get('/:id',async(req:AuthRequest,res)=>{try{const clinicId=req.user?.clinicId;if(!clinicId)return res.status(400).json({ok:false,error:'Клиника не указана'} satisfies ApiResponse);const p=await prisma.patient.findFirst({where:{id:req.params.id,clinicId},include:{visits:{orderBy:{date:'desc'}},appointments:{orderBy:{date:'desc'}},teeth:{orderBy:{number:'asc'}},treatmentPlans:{orderBy:{createdAt:'desc'}},images:{orderBy:{createdAt:'desc'}},documents:{orderBy:{createdAt:'desc'}}}});if(!p)return res.status(404).json({ok:false,error:'Пациент не найден'} satisfies ApiResponse);return res.json({ok:true,data:serializePatient(p)} satisfies ApiResponse)}catch(e){console.error('Get patient error:',e);return res.status(500).json({ok:false,error:'Ошибка при получении пациента'} satisfies ApiResponse)}});

patientsRouter.patch('/:id',requirePermission('patient.write'),requireClinicWritable,async(req:AuthRequest,res)=>{try{const clinicId=req.user?.clinicId;if(!clinicId)return res.status(400).json({ok:false,error:'Клиника не указана'} satisfies ApiResponse);const existing=await prisma.patient.findFirst({where:{id:req.params.id,clinicId}});if(!existing)return res.status(404).json({ok:false,error:'Пациент не найден'} satisfies ApiResponse);const body=req.body||{},names=(body.name||body.firstName||body.lastName)?splitName(body.name,body.firstName,body.lastName):{firstName:existing.firstName,lastName:existing.lastName};const prev=(existing.medicalHistory&&typeof existing.medicalHistory==='object'?existing.medicalHistory:{}) as Record<string,unknown>;const history={...prev,...(body.medicalHistory&&typeof body.medicalHistory==='object'?body.medicalHistory:{}),...(body.category!==undefined?{category:body.category}:{}),...(body.source!==undefined?{source:body.source}:{}),...(body.allergies!==undefined?{allergies:body.allergies}:{}),...(body.teeth!==undefined?{teeth:body.teeth}: {})};const p=await prisma.patient.update({where:{id:existing.id},data:{firstName:names.firstName,lastName:names.lastName,...(body.phone!==undefined?{phone:body.phone||null}:{}),...(body.email!==undefined?{email:body.email||null}:{}),...((body.dob||body.birthDate)!==undefined?{birthDate:(body.dob||body.birthDate)?new Date(body.dob||body.birthDate):null}:{}),...(body.gender!==undefined?{gender:body.gender||null}:{}),...(body.notes!==undefined?{notes:body.notes||null}:{}),...(body.address!==undefined?{address:body.address||null}:{}),medicalHistory:history as Prisma.InputJsonValue},include:{teeth:true}});if(body.teeth)await syncTeeth(p.id,body.teeth);const fresh=await prisma.patient.findUnique({where:{id:p.id},include:{teeth:true}});await auditFromReq(req,{action:'patient.updated',entity:'patient',entityId:p.id});return res.json({ok:true,data:serializePatient(fresh!)} satisfies ApiResponse)}catch(e){console.error('Update patient error:',e);return res.status(500).json({ok:false,error:'Ошибка при обновлении пациента'} satisfies ApiResponse)}});

patientsRouter.delete('/:id',requirePermission('patient.delete'),requireClinicWritable,async(req:AuthRequest,res)=>{try{const clinicId=req.user?.clinicId;if(!clinicId)return res.status(400).json({ok:false,error:'Клиника не указана'} satisfies ApiResponse);const p=await prisma.patient.findFirst({where:{id:req.params.id,clinicId}});if(!p)return res.status(404).json({ok:false,error:'Пациент не найден'} satisfies ApiResponse);await prisma.patient.delete({where:{id:p.id}});publish('patient.deleted',{clinicId,patientId:p.id,userId:req.user?.id});return res.json({ok:true,data:{id:p.id}} satisfies ApiResponse)}catch(e){console.error('Delete patient error:',e);return res.status(500).json({ok:false,error:'Ошибка при удалении пациента'} satisfies ApiResponse)}});

patientsRouter.get('/:id/history',async(req:AuthRequest,res)=>{try{const clinicId=req.user?.clinicId;if(!clinicId)return res.status(400).json({ok:false,error:'Клиника не указана'} satisfies ApiResponse);const p=await prisma.patient.findFirst({where:{id:req.params.id,clinicId},select:{id:true}});if(!p)return res.status(404).json({ok:false,error:'Пациент не найден'} satisfies ApiResponse);const page=parseInt(req.query.page as string)||1,limit=parseInt(req.query.limit as string)||20,{skip,take}=paginate(page,limit),where={patientId:p.id};const [rows,total]=await Promise.all([prisma.visit.findMany({where,skip,take,orderBy:{date:'desc'}}),prisma.visit.count({where})]);return res.json({ok:true,data:paginatedResponse(rows,total,page,limit)} satisfies ApiResponse)}catch(e){return res.status(500).json({ok:false,error:'Ошибка при получении истории визитов'} satisfies ApiResponse)}});

patientsRouter.get('/:id/images',async(req:AuthRequest,res)=>{try{const clinicId=req.user?.clinicId;if(!clinicId)return res.status(400).json({ok:false,error:'Клиника не указана'} satisfies ApiResponse);const p=await prisma.patient.findFirst({where:{id:req.params.id,clinicId},select:{id:true}});if(!p)return res.status(404).json({ok:false,error:'Пациент не найден'} satisfies ApiResponse);const images=await prisma.patientImage.findMany({where:{patientId:p.id},orderBy:{createdAt:'desc'}});return res.json({ok:true,data:images} satisfies ApiResponse)}catch(e){return res.status(500).json({ok:false,error:'Ошибка при получении изображений пациента'} satisfies ApiResponse)}});

patientsRouter.get('/:id/treatment-plan',async(req:AuthRequest,res)=>{try{const clinicId=req.user?.clinicId;if(!clinicId)return res.status(400).json({ok:false,error:'Клиника не указана'} satisfies ApiResponse);const p=await prisma.patient.findFirst({where:{id:req.params.id,clinicId},select:{id:true}});if(!p)return res.status(404).json({ok:false,error:'Пациент не найден'} satisfies ApiResponse);return res.json({ok:true,data:await prisma.treatmentPlan.findMany({where:{patientId:p.id},orderBy:{createdAt:'desc'}})} satisfies ApiResponse)}catch(e){return res.status(500).json({ok:false,error:'Ошибка при получении планов лечения'} satisfies ApiResponse)}});

patientsRouter.post('/:id/deposit',requireClinicWritable,async(req:AuthRequest,res)=>{try{const clinicId=req.user?.clinicId;if(!clinicId)return res.status(400).json({ok:false,error:'Клиника не указана'} satisfies ApiResponse);const amount=Number(req.body?.amount||0);if(!amount||Number.isNaN(amount))return res.status(400).json({ok:false,error:'Укажите сумму'} satisfies ApiResponse);const p=await prisma.patient.findFirst({where:{id:req.params.id,clinicId}});if(!p)return res.status(404).json({ok:false,error:'Пациент не найден'} satisfies ApiResponse);const next=Math.max(0,Number(p.prepaidBalance||0)+amount),updated=await prisma.patient.update({where:{id:p.id},data:{prepaidBalance:next},include:{teeth:true}});await auditFromReq(req,{action:'patient.deposit',entity:'patient',entityId:p.id,details:{amount,previousBalance:p.prepaidBalance,newBalance:next}});return res.json({ok:true,data:serializePatient(updated)} satisfies ApiResponse)}catch(e){return res.status(500).json({ok:false,error:'Не удалось пополнить баланс'} satisfies ApiResponse)}});

async function loadClinicPatient(req:AuthRequest,res:any){const clinicId=req.user?.clinicId;if(!clinicId){res.status(400).json({ok:false,error:'Клиника не указана'});return null}const p=await prisma.patient.findFirst({where:{id:req.params.id,clinicId},select:{id:true}});if(!p){res.status(404).json({ok:false,error:'Пациент не найден'});return null}return {clinicId,patientId:p.id};}
async function serializeAssignments(rows:any[]){if(!rows.length)return[];const users=await prisma.user.findMany({where:{id:{in:rows.map(r=>r.userId)}},select:{id:true,firstName:true,lastName:true,role:true,spec:true}});const m=new Map(users.map(u=>[u.id,u]));return rows.map(r=>{const u=m.get(r.userId);return{id:r.id,userId:r.userId,role:r.role,createdAt:r.createdAt,name:u?`${u.firstName} ${u.lastName}`.trim():'Сотрудник удалён',spec:u?.spec||null,systemRole:u?.role||null}})}

patientsRouter.get('/:id/assignments',async(req:AuthRequest,res)=>{try{const s=await loadClinicPatient(req,res);if(!s)return;const rows=await prisma.patientAssignment.findMany({where:{patientId:s.patientId,clinicId:s.clinicId,active:true},orderBy:{createdAt:'asc'},select:{id:true,userId:true,role:true,createdAt:true}});return res.json({ok:true,data:await serializeAssignments(rows)} satisfies ApiResponse)}catch(e){return res.status(500).json({ok:false,error:'Не удалось загрузить ответственных'} satisfies ApiResponse)}});
patientsRouter.post('/:id/assignments',requirePermission('patient.write'),requireClinicWritable,async(req:AuthRequest,res)=>{try{const s=await loadClinicPatient(req,res);if(!s)return;const userId=String(req.body?.userId||''),role=req.body?.role;if(!userId)return res.status(400).json({ok:false,error:'Укажите сотрудника'} satisfies ApiResponse);if(role!==undefined&&!isAssignmentRole(role))return res.status(400).json({ok:false,error:'Неизвестная роль'} satisfies ApiResponse);if(!(await isClinicMember(userId,s.clinicId)))return res.status(400).json({ok:false,error:'Сотрудник не работает в этой клинике'} satisfies ApiResponse);const written=await ensurePatientAssignment({clinicId:s.clinicId,patientId:s.patientId,userId,role});if(!written)return res.status(500).json({ok:false,error:'Не удалось назначить ответственного'} satisfies ApiResponse);await auditFromReq(req,{action:'patient.assignment.added',entity:'patient',entityId:s.patientId,details:{userId,role:role||'treating_doctor'}});const rows=await prisma.patientAssignment.findMany({where:{patientId:s.patientId,clinicId:s.clinicId,active:true},orderBy:{createdAt:'asc'},select:{id:true,userId:true,role:true,createdAt:true}});return res.status(201).json({ok:true,data:await serializeAssignments(rows)} satisfies ApiResponse)}catch(e){return res.status(500).json({ok:false,error:'Не удалось назначить ответственного'} satisfies ApiResponse)}});
patientsRouter.delete('/:id/assignments/:assignmentId',requirePermission('patient.write'),requireClinicWritable,async(req:AuthRequest,res)=>{try{const s=await loadClinicPatient(req,res);if(!s)return;const revoked=await revokePatientAssignment(s.clinicId,req.params.assignmentId);if(!revoked)return res.status(404).json({ok:false,error:'Назначение не найдено'} satisfies ApiResponse);await auditFromReq(req,{action:'patient.assignment.removed',entity:'patient',entityId:s.patientId,details:{assignmentId:req.params.assignmentId}});return res.json({ok:true,data:{id:req.params.assignmentId}} satisfies ApiResponse)}catch(e){return res.status(500).json({ok:false,error:'Не удалось снять ответственного'} satisfies ApiResponse)}});
